import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/ui/header";
import Progress from "@/components/Progress";
import Pointer from "@/components/Pointer";
import { cn } from "@/lib/utils";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "flex flex-col min-h-dvh")}>
        <Header />
        <Progress />
        <main className="flex-grow">
          {children}
          <Pointer />
        </main>
      </body>
    </html>
  );
}
